apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: advanceeq
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps:
    - name: shared-data
      namespace: ""
  environment:
    name: python
    namespace: ""
  functionTimeout: 240
  idletimeout: 120
  package:
    functionName: advanceeq.main
    packageref:
      name: advanceeq
      namespace: ""
  requestsPerPod: 1
  resources: {}
