include:
- ./fission/functions/queryfromelastic/weatherq.zip
kind: ArchiveUploadSpec
name: functions-weatherq-zip-PmaE

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: weatherq
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-weatherq-zip-PmaE
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-15T04:45:03Z"
