include:
- ./fission/functions/queryfromelastic/advanceeq.zip
kind: ArchiveUploadSpec
name: functions-advanceeq-zip-LRrL

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: advanceeq
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-advanceeq-zip-LRrL
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-12T15:54:57Z"
