include:
- ./fission/functions/analysis/canalysis.zip
kind: ArchiveUploadSpec
name: functions-canalysis-zip-i2nd

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: canalysis
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-canalysis-zip-i2nd
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-16T17:23:48Z"
