apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: ganalysis
spec:
  createingress: false
  functionref:
    functionweights: null
    name: ganalysis
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /ganalysis/fill/{fill}/startdate/{start}/enddate/{end}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /ganalysis/fill/{fill}/startdate/{start}/enddate/{end}
