apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: panalysis
spec:
  createingress: false
  functionref:
    functionweights: null
    name: panalysis
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /panalysis/year/{year}/pollen/{locationp}/weather/{locationw}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /panalysis/year/{year}/pollen/{locationp}/weather/{locationw}
