apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: advanceeq
spec:
  createingress: false
  functionref:
    functionweights: null
    name: advanceeq
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /advanceeq/indexname/{index}/date/{date}/location/{location}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /advanceeq/indexname/{index}/date/{date}/location/{location}
