apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: ianalysis
spec:
  createingress: false
  functionref:
    functionweights: null
    name: ianalysis
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /ianalysis
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /ianalysis
