apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: weatherq
spec:
  createingress: false
  functionref:
    functionweights: null
    name: weatherq
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /weather/year/{year}/month/{month}/day/{day}/location/{location}/weatherstat/{weather}/bymonth/{bymonth}/index/{index}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /weather/year/{year}/month/{month}/day/{day}/location/{location}/weatherstat/{weather}/bymonth/{bymonth}/index/{index}
