apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: canalysis
spec:
  createingress: false
  functionref:
    functionweights: null
    name: canalysis
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /canalysis/year/{year}/crash/{locationc}/weather/{locationw}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /canalysis/year/{year}/crash/{locationc}/weather/{locationw}
