apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: test-params
data:
  ES_URL: 'https://elasticsearch-master.elastic.svc.cluster.local:9200'
  ES_USERNAME: elastic
  ES_PASSWORD: elastic
  ES_DATABASE: 'weathertest'
  ES_SCHEMA: |
    {
      "settings": {
        "index": {
          "number_of_shards": 3,
          "number_of_replicas": 2
        }
      },
      "mappings": {
        "properties": {
          "id": {
            "type": "keyword"
          },
          "location": {
            "type": "text"
          },
          "date": {
            "type": "text"
          },
          "minTemp": {
            "type": "float"
          },
          "maxTemp": {
            "type": "float"
          },
          "rain": {
            "type": "float"
          },
          "year": {
            "type": "integer"
          },
          "month": {
            "type": "integer"
          },
          "day": {
            "type": "integer"
          }
        }
      }
    }
